TrackableEntities/trackable-entities

Source/Tests/TrackableEntities.Client.Tests.Entities/Mocks/MockNorthwind.cs, Source/Tests/TrackableEntities.Client.Tests.Entities/NorthwindModels/Product.cs, Source/Tests/TrackableEntities.Client.Tests.Entities/NorthwindModels/PromotionalProduct.cs, Source/Tests/TrackableEntities.Client.Tests.Entities/TrackableEntities.Client.Tests.Entities.csproj, Source/Tests/TrackableEntities.Client.Tests.Extensions/ChangeTrackingExtensionsTests.cs, Source/Tests/TrackableEntities.Client.Tests.Extensions/TrackableExtensionsTests.cs, Source/TrackableEntities.Client/TrackableExtensions.cs
Hello Tony and happy new year!
I finally found some time to look at the shortcomings we have with inherited entities. Problems mentioned in http://trackable.codeplex.com/discussions/552553#PostContent_1278793 and http://trackable.codeplex.com/discussions/552553#PostDetailsCell_1278860 still seem to be valid.
I'm currently working on a more radical solution, but for now would like you to have a look at the following PR which fixes a few obvious glitches in
* TrackableExtensions.CloneObject
* TrackableExtensions.GetChangeTrackingProperty
* TrackableExtensions.GetEquatableMethod
* TrackableExtensions.GetEntityIdentifierProperty
It also reveals the shortcoming in the ModelBase class, which doesn't allow us to call its NotifyPropertyChanged method from the inherited entity (commit …
=> Inheritance: cosmetic improvements and remaining shortcomings

Source/Tests/TrackableEntities.Client.Tests.Extensions/TrackableExtensionsTests.cs, Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionWithChildrenTests.cs, Source/TrackableEntities.Client/TrackableExtensions.cs
I found and fixed a bug with SetModifiedProperties which has been around a while.  When removing a child entity, ModifiedProperties is cleared from sibling entities because SetModifiedProperties, which is called from RemoveItem in CT collection, sets ModifiedProperties for 1-M and M-M related entities to null.
@azabluda Let me know if you have any thoughts on this.
=> [Bug] SetModifiedProperties Should Not Affect Parent or Sibling Entities

Source/Tests/TrackableEntities.EF.5.Tests/NorthwindDbContextTests.cs, Source/TrackableEntities.EF.5/DbContextExtensions.cs
Added failing test in NorthwindDbContextTests:
Apply_Changes_Should_Mark_Unchanged_Employee_As_Unchanged_And_Added_Territories_Without_Employee_As_Unchanged
- Exception thrown when adding child m2m entity without link back to parent.
Exception takes place when setting relationship state of child entities, because parent entity has not yet been attached to context. This bug takes place in v2.2 but not 2.1.
=> [Bug] DbContext.ApplyChanges Throws Exception when Adding Child M2M Entity

Source/Tests/TrackableEntities.EF.5.Tests/NorthwindDbContextTests.cs
Hi Tony,
Volker has encountered a bug in ApplyChanges yesterday, which I managed to strip down to a relatively simple unit test.
In Northwind terms it is a new Order with one new OrderDetail associated with an existing (unchanged) Product. Exactly how new orders are placed in real life. Strangely ApplyChanges marks Product as Added, which causes EF6 to INSERT it leading to PK index violation.
Could you please look into this problem?
Thanks,
Alexander
P.S: not sure if PR is the right way of submitting problems without any proposed solutions...
=> Unable to place a new order for an existing product

Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionTests.cs, Source/TrackableEntities.Client/ChangeTrackingCollection.cs, Source/TrackableEntities.Client/ITrackingCollection.cs, Source/TrackableEntities.Client/TrackableExtensions.cs
When the ```Remove``` method is called on ```ChangeTrackingCollection<T>```, change tracking for related entities is not disabled properly. It should only be disabled for 1-M relations, but not for 1-1, M-1 or M-M.  This is what is causing the problem described in #56.
I have added tests for this desired conditions.  Then I implemented a fix.
=> Remove Method on ChangeTrackingCollection<T>: Disable Change Tracking

Source/Tests/TrackableEntities.EF.5.Tests/FamilyDbContextTests.cs
Hi Tony,
I've encountered one more issue in ApplyChanges extension method. It fails to propagate State=Deleted into the 2nd level child entity if the 1st level child is also deleted. In the real database scenarios it provokes EF exception in DbContext.SaveChanges
```
System.InvalidOperationException occurred
HResult=-2146233079
Message=The operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted.
Source=EntityFramework
StackTrace:
at …
```
=> ApplyChanges should mark grandchild deleted

Source/Tests/TrackableEntities.EF.5.Tests/LoadRelatedEntitiesTests.cs, Source/TrackableEntities.EF.5/DbContextExtensions.cs
Fixes issue #90.
Cloned visitationHelper passed to context.ApplyChangesOnProperties on line 161.
Updated subsequent calls to context.ApplyChangesOnProperties to use non-Cloned visitationHelper on last call.
=> [#90 Fix] ApplyChanges should mark grandchild deleted

Source/Tests.Acceptance/TrackableEntities.Tests.Acceptance/TrackableEntities.Tests.Acceptance.csproj, Source/Tests/TrackableEntities.EF.5.Tests/Contexts/NorthwindDbContext.cs, Source/Tests/TrackableEntities.EF.5.Tests/LoadRelatedEntitiesTests.cs, Source/Tests/TrackableEntities.EF.5.Tests/NorthwindModels/HolidayPromo.cs, Source/Tests/TrackableEntities.EF.5.Tests/NorthwindModels/Product.cs, Source/Tests/TrackableEntities.EF.5.Tests/NorthwindModels/Promo.cs, Source/Tests/TrackableEntities.EF.5.Tests/TrackableEntities.EF.5.Tests.csproj, Source/Tests/TrackableEntities.EF.6.Tests/TrackableEntities.EF.6.Tests.csproj, Source/TrackableEntities.EF.5/DbContextExtensions.cs
When a type has a reference type which derives from a bass class, then DbContext.LoadRelatedEntities throws an exception because there is a missing table name in the resulting Entity SQL.
I have corrected the problem with this pull request and included a test which verifies the fix.
=> Load Related Entities for Derived Reference Types

Source/Tests.Acceptance/TrackableEntities.Tests.Acceptance/TrackableEntities.Tests.Acceptance.csproj, Source/Tests/TrackableEntities.EF.5.Tests/Contexts/NorthwindDbContext.cs, Source/Tests/TrackableEntities.EF.5.Tests/LoadRelatedEntitiesTests.cs, Source/Tests/TrackableEntities.EF.5.Tests/NorthwindModels/Product.cs, Source/Tests/TrackableEntities.EF.5.Tests/NorthwindModels/ProductInfo.cs, Source/Tests/TrackableEntities.EF.5.Tests/TrackableEntities.EF.5.Tests.csproj, Source/Tests/TrackableEntities.EF.6.Tests/TrackableEntities.EF.6.Tests.csproj, Source/TrackableEntities.EF.5/DbContextExtensions.cs
Added support to DbContext.LoadRelatedEntities for reference types that have composite primary keys, that is, keys which consist of more than one property.
This resolved #83 Support for multiple primary keys for reference types.
=> Add Support to LoadRelatedEntities for Composite Keys

Source/Tests.Acceptance/TrackableEntities.Tests.Acceptance/app.config, Source/Tests/TrackableEntities.EF.5.Tests/App.config, Source/Tests/TrackableEntities.EF.6.Tests/App.config
I added *commented* configuration parameters for EntityFramework to be able to use LocalDB. Developer has to uncomment this new section and comment section for SQL Express (or Full) to run tests.
=> Added configuration parameters for LocalDB in test projects.

Source/TrackableEntities.sln.DotSettings
Added team-shared solution level settings for [ReSharper] (https://www.jetbrains.com/resharper/). These settings meet some of coding guidelines that are adjustable in R#. Inspection severity for these rules is set to *Warning*.
(@tonysneed - I cannot found your coding guidelines referencing [Coding Guidelines for ASP.NET int GitHub] (https://github.com/aspnet/Home/wiki/Engineering-guidelines#coding-guidelines). Where is the reference?)
These coding guidelines was applied:
1. Use **_camelCase** for private fields.
2. Avoid **this.** unless absolutely necessary
3. Always specify **member visiblity**, even if it's the default (i.e. private string _foo; not string _foo;)
4. The **var** keyword is to be used as much as the compiler will allow. 
5. When using a type that has a **C# keyword** …
=> Add ReSharper settings for coding guidelines.

Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionTests.cs, Source/TrackableEntities.Client/ChangeTrackingCollection.cs
This PR includes failing test from PR #136 from @MarcDrexler, which shows that calling `GetChanges` on employee.Territories with a `_deleted` item adds it back to the Territories collection.
The probable cause of this behavior is that removing an Added territory sets its state to Unchanged and adds it to the `_deleted` collection, as described in issue #132.
The problem is in the `RemoveItem` method of `ChangeTrackingCollection`, where items are added to `_deleted` if their state is not set to Added.  Because the removed territory has had its state set to Unchanged, it is added to `_deleted`.  Setting the state to Unchanged is correct for M-M relations, so we need to capture that its original state was Added, and then **not** add it to `_deleted`.
The code in question is …
=> Adding Removed M-M Item Adds It to _deleted Collection

Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionTests.cs, Source/TrackableEntities.Client/TrackableExtensions.cs
The problem is with the part of `TrackableExtensions.RemoveRestoredDeletes`, which attempts to remove deletes which were temporarily restored:
```csharp
var removedDeletes = changeTracker.GetChanges(true).Cast<ITrackable>().ToList();
if (item.TrackingState == TrackingState.Deleted)
{
var isTracking = changeTracker.Tracking;
changeTracker.Tracking = false;
if (removedDeletes.Contains(item))
items.Remove(item);
changeTracker.Tracking = isTracking;
}
```
Calling `changeTracker.GetChanges` again here seems to be the source of the problem.  Instead the `items.RemoveAt(i)` should be called.
=> Fix #139: ChangeTrackingCollection is modified when calling GetChanges

Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionTests.cs
I found another one 😄 
Assuming somebody calls GetChanges several times to check if the data is dirty, the return value of GetChanges will become incorrect.
After removing 3 territories from an employee, GetChanges should return 3 territories with TrackingState Deleted, no matter how often GetChanges has been called before.
The following line in the new test will fail:
`Assert.Equal(3, changes[0].Territories.Count); `
I think you can reopen #139
=> Calling GetChanges multiple times does not capture additional changes

Source/Tests/TrackableEntities.Client.Tests.Extensions/ChangeTrackingExtensionsTests.cs, Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionTests.cs, Source/TrackableEntities.Client/ChangeTrackingCollection.cs, Source/TrackableEntities.Client/ChangeTrackingExtensions.cs, Source/TrackableEntities.Client/ITrackingCollection.cs, Source/TrackableEntities.Client/TrackableExtensions.cs
Fixed problem with `GetChanges` which resulted in additional changes not being recorded.  The cause was that tracking had been turned in M-M entities in the object graph through recursion.
To solve the problem, I created a write-only `InternalTracking` property for setting Tracking without graph traversal and recursion.
While I was at it, I also simplified the `GetChanges` method on `ITrackingCollection` to remove the  `cachedDeletesOnly` parameter, and added a `CachedDeletes` property, so that cached deletes could be retrieved without creating a new ChangeTrackingCollection.
=> Fix #141: Calling GetChanges multiple times does not capture additional changes

Source/Tests/TrackableEntities.EF.5.Tests/App.config, Source/Tests/TrackableEntities.EF.6.Tests/App.config
Since VS' default SQL Server is LocalDB, and to spare the hassle of installing SQL Express.
=> Change connection strings to use local db

Source/TrackableEntities.Client.Net45/EntityBaseNet45.cs, Source/TrackableEntities.Client/EntityBase.cs
Added NPC into the main BaseEntity, so portable classes also get the `CallerMemberName` attribute if they're above .NET 4.5.
Fixes #161.
=> Added NPC into the main BaseEntity

Source/Tests/TrackableEntities.Client.Tests.Extensions/ChangeTrackingExtensionsTests.cs, Source/TrackableEntities.Client/ChangeTrackingExtensions.cs
There are 4 failing test that need to be fixed.
- Run all the tests to see which ones are failing.
=> Revert "Added a fix to ignore merging changes of unidentifiable entities."

Source/Tests/TrackableEntities.EF.5.Tests/Contexts/FamilyDbContext.cs, Source/Tests/TrackableEntities.EF.5.Tests/FamilyModels/Contact.cs, Source/Tests/TrackableEntities.EF.5.Tests/FamilyModels/ContactDetail.cs, Source/Tests/TrackableEntities.EF.5.Tests/LoadRelatedEntitiesTests.cs, Source/Tests/TrackableEntities.EF.5.Tests/TrackableEntities.EF.5.Tests.csproj, Source/Tests/TrackableEntities.EF.6.Tests/TrackableEntities.EF.6.Tests.csproj
LoadRelatedEntities throws an exception when foreign key name does not match related primary key name.
Fixes #197.
Replaces #205.
=> Fix LoadRelatedEntities with Non-Matching Foreign Keys

Source/Tests/TrackableEntities.EF.5.Tests/FamilyModels/Contact.cs, Source/Tests/TrackableEntities.EF.5.Tests/LoadRelatedEntitiesTests.cs, Source/TrackableEntities.EF.5/DbContextExtensions.cs
- Revert commit d2bb2336 so that 1-1 with non-matching keys throws.
- Resolves issue #165.
=> Add onLoading, onError callbacks to LoadRelatedEntities.

Source/TrackableEntities.Client/ChangeTrackingCollection.cs
To avoid possibility of having duplicate property names.
=> Changed ModifiedProperties default initialization to HashSet<string>
